name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Save secret key to file
        run: echo "${{ secrets.key }}" > ./Config/key.json

      - name: Authenticate with Google Cloud
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ./Backend/Config/key.json
        run: |
          gcloud auth activate-service-account --key-file=./Backend/Config/key.json

      - name: Deploy to Google Cloud
        run: gcloud app deploy
